// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_AIIMAGINEAGENT_H_
#define _BEHAVIAC_AIIMAGINEAGENT_H_

#include "Behaviac/internal/behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

class AiImagineAgent : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE AiImagineAgent
///<<< END WRITING YOUR CODE
{
public:
	AiImagineAgent();
	virtual ~AiImagineAgent();

	BEHAVIAC_DECLARE_AGENTTYPE(AiImagineAgent, behaviac::Agent)

public: 
	void SayHello();
public: 
	void SayHelloWorld();
	behaviac::EBTStatus MoveEntity(std::string name, double pos_x, double pos_y,double dir);
	void Start() {}
	void End();
	void Wait()  {}

///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
