// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_AIIMAGINEAGENT_H_
#define _BEHAVIAC_AIIMAGINEAGENT_H_

#include "Behaviac/internal/behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

class AiImagineAgent : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE AiImagineAgent
///<<< END WRITING YOUR CODE
{
public:
	AiImagineAgent();
	virtual ~AiImagineAgent();

	BEHAVIAC_DECLARE_AGENTTYPE(AiImagineAgent, behaviac::Agent)

public: 
	void SayHello();
public: 
	void SayHelloWorld();
	behaviac::EBTStatus MoveEntity(std::string name, double pos_x, double pos_y,double dir);
	void Start() {}
	void End();
	void Wait()  {}
	void MoveBackEntity(behaviac::string EntityName, double PosX, double PosY, double PosZ, int Dir);
	void PlayAnimation(behaviac::string EntityName, behaviac::string ActionName);
	void Fire(behaviac::string EntityName, bool IsFire);
	void CreateCamera(double posx, double posy, double posz, int dir);
	behaviac::EBTStatus OpenCabinAnimation(behaviac::string EntityName, int EntityType);
	behaviac::EBTStatus UnInstallBoatAnimation();
	behaviac::EBTStatus ClosedCabinAnimation(behaviac::string EntityName, int EntityType);
	
///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
