// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_PROPERTIES_H_
#define _BEHAVIAC_AGENT_PROPERTIES_H_

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }
	inline void FunctionPointer_AiImagineAgent_End(Agent* self) { ((AiImagineAgent*)self)->End(); }
	inline void FunctionPointer_AiImagineAgent_LogMessage(char* param0) { AiImagineAgent::LogMessage(param0); }
	inline behaviac::EBTStatus FunctionPointer_AiImagineAgent_MoveEntity(Agent* self, behaviac::string entityname, double posx, double posy, double dir) { return ((AiImagineAgent*)self)->MoveEntity(entityname, posx, posy, dir); }
	inline void FunctionPointer_AiImagineAgent_SayHello(Agent* self) { ((AiImagineAgent*)self)->SayHello(); }
	inline void FunctionPointer_AiImagineAgent_SayHelloWorld(Agent* self) { ((AiImagineAgent*)self)->SayHelloWorld(); }
	inline void FunctionPointer_AiImagineAgent_Start(Agent* self) { ((AiImagineAgent*)self)->Start(); }
	inline void FunctionPointer_AiImagineAgent_Wait(Agent* self) { ((AiImagineAgent*)self)->Wait(); }
}
#endif // _BEHAVIAC_AGENT_PROPERTIES_H_
